---
title: "headfixed_rotary_operant_ratio_extraction"
author: "adam gordon-fennell"
date: "04/16/2021"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    toc_depth: 4
---




# setup
## kniter
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = TRUE)
```

## libraries
```{r, echo = TRUE}
library(tidyverse)
library(viridis)
library(lubridate)
library(janitor)
library(feather) # if using feather format
library(ggh4x) # force_panelsizes
library(ggbeeswarm)
library(afex) # aov
library(emmeans) # posthoc
library(patchwork) 
```

## sources
```{r}
dir_source <- './functions/'

source_files <- c('r_general.R', 'r_head_fixed_processing.R', 'r_head_fixed_plots.R')

source_functions <- function(){
  for(source_file in source_files){
    source(str_c(dir_source, source_file))
    }
}

source_functions()
```

# extract and pre process data data
## setup
```{r, echo = TRUE}
# directories 
dir_raw <- './example_data/raw/'
dir_extraction <- './example_data/extracted/'
dir_processed <- './example_data/processed/'
dir_analysis <- './example_data/analysis/'

# file format ('csv', or 'feather')
file_format_output <- 'csv'

# data logs and keys
log_data <- read_csv('log_data.csv', na = 'NA', col_types = cols())
log_multi_spout_ids <-  read_csv('log_multi_spout_ids.csv', na = 'NA', col_types = cols())
key_events <-  read_csv('key_events.csv',na = 'NA',  col_types = cols())
```

## extract and tidy data
```{r}
# Universal extraction and tidying script
extract_serial_output(
  dir_raw,                       # directory of the raw csv output from the arduino
  key_events,                    # key for decoding raw data
  dir_extraction,                # directory for the tidy datasets to be saved to
  manual_experiments = c('abb'), # optional- experiment string to process a single experiment
  manual_blocknames = NA,        # optional- use a vector of strings to specify individual sessions to process 
  file_format_output,            # file format (csv or feather)
  overwrite = 1                  # 0: only process new files in dir_raw, 1: process all files found in dir_raw and overwrite data in dir_extraction
  )
```


## pre processing
```{r, messages = FALSE}
# Pre processing for multi-spout data (not universal)

# setup files to process
manual_fns <- log_data %>%
  filter(procedure %>% str_detect('multi_')) %>%
  pull(blockname)

# process data
process_multi_spout(
  dir_extraction,                # directory for tidy datasets
  dir_processed,                 # directory for processed datasets produced by this function
  log_data,                      # log of behavioral data
  log_multi_spout_ids,           # log of multi-spout pairings 
  file_format_output = 'csv',    # file format (csv or feather)
  manual_fns,                    # optional- use a vector of strings to specify individual sessions to proces (otherwise use independent folders)
  overwrite = 1,                 # 0: only process new files in dir_extraction, 1: process all files found in dir_extraction and overwrite data in dir_processed
  time_bin_width = 100,          # bin width (ms) for binned average of licking during access
  time_bin_range = c(0,3000),    # time range (ms) for the access period
  session_trial_width = 10,      # bin width (trials) for licking across trials (e.g. 10 for blocks of 10 trials / bin)
  session_trial_range = c(0,100) # trial range (trials) for the trials (e.g. c(0, 100) for 100 trials)
  )
```

# data visualization
## summaries of individual sessions
```{r, messages = FALSE}
# optional
# batch_session_plt_multi_spout_summary(
#   dir_processed,                  # directory for data produced by process_multi_spout
#   dir_extraction,                 # directory for data produced by extract_serial_output
#   file_format = 'csv',            # file format (csv or feather)
#   manual_blocknames = manual_fns, # optional- use a vector of strings to specify individual sessions to proces
#   overwrite = 0                   # 0: only plot new data, 1: plot all data and overwrite
#   )
```

## groupped summaries
```{r, message = FALSE, fig.height = 9, fig.width=12}
source_functions()

# setup the sessions to be included
analysis_fns <- log_data %>%
  filter(procedure == 'multi_s') %>%
  filter(deprivation == 'wr') %>%
  pull(blockname)

# return summary plot for files specified in analysis_fns
plt_wr <- combined_plt_multi_spout_summary(
  dir_extracted = dir_extraction,
  analysis_fns = analysis_fns,
  log_data = log_data,
  analysis_id = 'multi_s', 
  dir_output = dir_analysis,
  file_format = 'csv')

plt_wr 


analysis_fns <- log_data %>%
  filter(procedure == 'multi_s') %>%
  filter(deprivation == 'fr') %>%
  pull(blockname)

plt_fr <- combined_plt_multi_spout_summary(
  dir_extracted = dir_extraction,
  analysis_fns = analysis_fns,
  log_data = log_data,
  analysis_id = 'multi_s', 
  dir_output = dir_analysis,
  file_format = 'csv')

analysis_fns <- log_data %>%
  filter(procedure == 'multi_nacl') %>%
  pull(blockname)

plt_nacl <- combined_plt_multi_spout_summary(
  dir_extracted = dir_extraction,
  analysis_fns = analysis_fns,
  log_data = log_data,
  analysis_id = 'multi_nacl', 
  dir_output = dir_analysis,
  file_format = 'csv')


plt_wr / plt_fr / plt_nacl

```


